### ISSUE TITLE
DZ09 cpu variants.

### ISSUE THREAD

**Issue by astro826** [MediatekInfo/DZ09#6]
Your project is amazing.
I have a problem, help me.
In your project, the core chip is MT6261A, but there are DZ09 variants which have MT6261D as a core.
I hope your project works well with these watches.
What do you think about this issue?

**Comment by MediatekInfo** [comment]
Hi!
The difference between MT6261A and MT6261D is minimal. MT6261A uses an external flash memory chip, MT6261D uses an internal (4 MiB) chip. No other differences were found. You can change the size of the flash memory in the MT6261A.ld linker script file, ROM region.
I am not sure that my project will work with other watches, because a huge number of clones with the name DZ09 have been released with different schematics and external peripherals. C'est la vie.

**Comment by astro826** [comment]
Merci de votre message.
________________________________
